### ISSUE TITLE
Django 3.0.6 exception middleware TypeError: PaginationMiddleware() takes no arguments

### ISSUE THREAD

**Issue by olamigokayphils** [staticdev/django-pagination-bootstrap#102]
Installing the pagination middleware on Django 3.0.6 throws a Type error 
```
MIDDLEWARE_CLASSES = (
    # other middleware
    "django_pagination_bootstrap.middleware.PaginationMiddleware",
)
```

Error : `TypeError: PaginationMiddleware() takes no arguments`

**Comment by staticdev** [comment]
@olamigokayphils can you please put here the full stacktrace?

**Comment by olamigokayphils** [comment]
```
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/olamigokayphils/Desktop/Office/myapp_svr/venv/lib/python3.8/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/home/olamigokayphils/Desktop/Office/myapp_svr/venv/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 137, in inner_run
    handler = self.get_handler(*args, **options)
  File "/home/olamigokayphils/Desktop/Office/myapp_svr/venv/lib/python3.8/site-packages/django/contrib/staticfiles/management/commands/runserver.py", line 27, in get_handler
    handler = super().get_handler(*args, **options)
  File "/home/olamigokayphils/Desktop/Office/myapp_svr/venv/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 64, in get_handler
    return get_internal_wsgi_application()
  File "/home/olamigokayphils/Desktop/Office/myapp_svr/venv/lib/python3.8/site-packages/django/core/servers/basehttp.py", line 45, in get_internal_wsgi_application
    return import_string(app_path)
  File "/home/olamigokayphils/Desktop/Office/myapp_svr/venv/lib/python3.8/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/olamigokayphils/Desktop/Office/myapp_svr/src/myapp/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/olamigokayphils/Desktop/Office/myapp_svr/venv/lib/python3.8/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    return WSGIHandler()
  File "/home/olamigokayphils/Desktop/Office/myapp_svr/venv/lib/python3.8/site-packages/django/core/handlers/wsgi.py", line 127, in __init__
    self.load_middleware()
  File "/home/olamigokayphils/Desktop/Office/myapp_svr/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 37, in load_middleware
    mw_instance = middleware(handler)
TypeError: PaginationMiddleware() takes no arguments

```

**Comment by staticdev** [comment]
Thanks for your report @olamigokayphils, we will release a bugfix release ASAP.

**Comment by staticdev** [comment]
@olamigokayphils please try this new release https://github.com/staticdev/django-pagination-bootstrap/releases/tag/v2.3.1
I hope you don't get any errors now.
