### ISSUE TITLE
v1.2.2 without requirements.txt in the pypi package

### ISSUE THREAD

**Issue by urtzai** [staticdev/django-pagination-bootstrap#27]
setup.py references requirements.txt. Please, add requirements.txt in the package or remove the file and add dependencies in setup.py

**Comment by shadiakiki1986** [comment]
Same issue here:
```
pip install -U django-pagination-bootstrap
Collecting django-pagination-bootstrap
  Downloading django-pagination-bootstrap-1.2.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/home/shadi/.local/share/virtualenvs/SIC_NAMECHECK/lib/python3.5/site-packages/pip/download.py", line 421, in get_file_content
        with open(url, 'rb') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-d5niuiip/django-pagination-bootstrap/setup.py", line 43, in <module>
        install_requires=get_requirements('requirements.txt'),
      File "/tmp/pip-build-d5niuiip/django-pagination-bootstrap/setup.py", line 22, in get_requirements
        required = set([str(ir.req) for ir in install_reqs])
      File "/tmp/pip-build-d5niuiip/django-pagination-bootstrap/setup.py", line 22, in <listcomp>
        required = set([str(ir.req) for ir in install_reqs])
      File "/home/shadi/.local/share/virtualenvs/SIC_NAMECHECK/lib/python3.5/site-packages/pip/req/req_file.py", line 84, in parse_requirements
        filename, comes_from=comes_from, session=session
      File "/home/shadi/.local/share/virtualenvs/SIC_NAMECHECK/lib/python3.5/site-packages/pip/download.py", line 425, in get_file_content
        'Could not open requirements file: %s' % str(exc)
    pip.exceptions.InstallationError: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-d5niuiip/django-pagination-bootstrap/
```
but this works
```
pip install -U django-pagination-bootstrap==1.2.1
Collecting django-pagination-bootstrap==1.2.1
  Downloading django-pagination-bootstrap-1.2.1.tar.gz
Requirement already up-to-date: Django>=1.7.0 in /home/shadi/.local/share/virtualenvs/SIC_NAMECHECK/lib/python3.5/site-packages (from django-pagination-bootstrap==1.2.1)
Building wheels for collected packages: django-pagination-bootstrap
  Running setup.py bdist_wheel for django-pagination-bootstrap ... done
  Stored in directory: /home/shadi/.cache/pip/wheels/03/51/85/f886225e6d91514a192d792a61cd991358db39aff81dfd9caa
Successfully built django-pagination-bootstrap
Installing collected packages: django-pagination-bootstrap
  Found existing installation: django-pagination-bootstrap 1.1
    Uninstalling django-pagination-bootstrap-1.1:
      Successfully uninstalled django-pagination-bootstrap-1.1
Successfully installed django-pagination-bootstrap-1.2.1
```

**Comment by staticdev** [comment]
This is strange, something wrong with PyPi packing. I will try republising tomorrow as version 1.2.3 (can't do this today).

**Comment by staticdev** [comment]
Done @urtzai @shadiakiki1986
